CREATE TABLE IF NOT EXISTS singer (
id BIGINT PRIMARY KEY,
name VARCHAR(255) NOT NULL);


CREATE TABLE IF NOT EXISTS album (
id BIGINT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
genre VARCHAR(255) NOT NULL,
singer_id BIGINT NOT NULL,
FOREIGN KEY (singer_id) REFERENCES singer (id) ON UPDATE CASCADE ON DELETE CASCADE);


CREATE TABLE IF NOT EXISTS song (
id BIGINT PRIMARY KEY,
title VARCHAR(255) NOT NULL,
duration VARCHAR(20) NOT NULL,
singer_id BIGINT NOT NULL,
album_id BIGINT,
FOREIGN KEY (singer_id) REFERENCES singer (id) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (album_id) REFERENCES album (id) ON UPDATE CASCADE);